
version: 2.1  # CircleCI configuration version

jobs:
  test:
    docker:
      - image: cimg/node:22.4.0  
    steps:
      - checkout  # Checkout your source code repository
      - run: | 
         echo "hello world"
         node --version
      - run: | 
          kubectl version
          
workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - test
