
Copy code
version: 2.1  # CircleCI configuration version

jobs:
  hello_world_job:
    docker:
      - image: circleci/python:3.9  # Example Docker image with Python 3.9
    steps:
      - checkout  # Checkout your source code repository
      - run:
          name: Print Hello, World!
          command: echo "Hello, World!"
          
workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - hello_world_job