
version: 2.1  # CircleCI configuration version

jobs:
  build_and_push :
    docker:
      - image: circleci/python:3.9  # Example Docker image with Python 3.9
    steps:
      - checkout  # Checkout your source code repository
      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: creating the image 
          command: |
            docker build -t prajwlas0209/circle-test:latest  .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push prajwlas0209/circle-test:latest

          
workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - build_and_push