
version: 2.1  # CircleCI configuration version

jobs:
  build_and_push :
    docker:
      - image: circleci/nginx  # Example Docker image with Python 3.9
    steps:
      - checkout  # Checkout your source code repository
      - run:
          name: creating the image 
          command: docker build image -t foobar .

      - run:
          name: printing the message
          command: echo "docker image built sucessfully"
          
workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - build_and_push