version: 2.1  # CircleCI configuration version

executors:
  docker_push:
    environment:
      DOCKER_USERNAME: prajwalhugar33@gmail.com
      DOCKER_PASSWORD: 022002Praju@9902
    docker:
      - image: cimg/node:22.4.0

jobs:
  test:
    executor: docker_push
    steps:
      - checkout  # Checkout your source code repository
      - setup_remote_docker
      - run:
          name: Building the image 
          command: docker image build -t prajwlas0209/circle-test:v1 .
      - run:
          name: Logging to Docker Hub 
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Pushing to Docker Hub
          command: docker push prajwlas0209/circle-test:v1

workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - test
