
version: 2.1  # CircleCI configuration version
executors:
  test-exec:
    environment:
      IMAGE_NAME:
     docker:
      - image: cimg/node:22.4.0  
      
jobs:
  test:
   test-exec:
      - checkout  # Checkout your source code repository
      - run: | 
         echo "hello world"
         node --version
          
workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - test
