version: 2.1  # CircleCI configuration version

executors:
  docker_push:
    environment:
      DOCKER_USERNAME: prajwalhugar33@gmail.com
      DOCKER_PASSWORD: 022002Praju@9902
    docker:
      - image: cimg/node:22.4.0

jobs:
  git_checkout:
    executor: docker_push
    steps:
    - checkout 

  settingup_docker:
    executor: docker_push
    steps: 
      - setup_remote_docker 

  buildandpush_docker:
    executor: docker_push
    steps: 
    - run:
        name: Building the image 
        command: docker image build -t prajwlas0209/circle-test:v1 .
    - run:
        name: Logging to Docker Hub 
        command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run:
        name: Pushing to Docker Hub
        command: docker push prajwlas0209/circle-test:v1

workflows:
  version: 2
  hello_world_workflow:
    jobs:
      - git_checkout
      - settingup_docker
      - buildandpush_docker
