version: 2.1

jobs:
  build:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout  # Check out the code from your repository

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: docker build -t my-nginx-app .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker tag my-nginx-app $DOCKERHUB_USERNAME/my-nginx-app:latest
            docker push $DOCKERHUB_USERNAME/my-nginx-app:latest


  deploy:
    docker:
      - image: circleci/python:3.8  # Base image to run deployment steps
    steps:
      - checkout  # Check out the code from your repository

      - run:
          name: Install kubectl
          command: |
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl

      - run:
          name: Configure kubectl
          command: |
            mkdir -p $HOME/.kube
            echo $KUBECONFIG_CONTENT > $HOME/.kube/config

      - run:
          name: Deploy to Kubernetes
          command: kubectl apply -f k8s/deployment.yaml

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
